"""
MicroSmart PF - Reasoning Agent
-------------------------------
This module interfaces with the Cerebras Inference API (Llama 3.3) to provide
clinical interpretation of quantitative data generated by the Vision Agent.

Author: MicroSmart Team
"""

import os
import logging
from cerebras.cloud.sdk import Cerebras
from src import config

logger = logging.getLogger(__name__)

class BrainAgent:
    def __init__(self):
        self.client = Cerebras(api_key=os.environ.get("CEREBRAS_API_KEY"))
        self.model = "llama-3.3-70b"

    def generate_report(self, vision_data: dict) -> str:
        # Extract Data
        counts = vision_data.get('detailed_counts', {})
        parasitemia = vision_data.get('parasitemia_calculation', {}).get('value', 'N/A')
        total = vision_data.get('total_parasites', 0)

        user_prompt = f"""
        DATA INPUT:
        - Parasitemia: {parasitemia}
        - Total Parasites: {total}
        - Breakdown: {counts}
        
        Generate a diagnostic summary.
        """

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": config.SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.1
            )
            return response.choices[0].message.content
        except Exception as e:
            logger.error(f"Brain Error: {e}")
            return "Error: MicroSmart reasoning engine unavailable."