import React from 'react';
import { ShieldAlert, Github } from 'lucide-react';

interface FooterProps {
  compact?: boolean;
}

export const Footer: React.FC<FooterProps> = ({ compact = false }) => {
  return (
    <footer className={`bg-slate-950 border-t border-slate-900 relative z-10 ${compact ? 'py-4' : 'py-12'}`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Main Content (Hidden in ultra-compact mode if needed, but we keep it slim here) */}
        {!compact ? (
          // FULL FOOTER (Landing Page)
          <div className="flex flex-col md:flex-row gap-12 items-start justify-between">
            <div className="max-w-md">
              <h4 className="text-slate-100 font-bold mb-3 tracking-tight">MicroSmart Research Initiative</h4>
              <p className="text-sm text-slate-500 leading-relaxed mb-6">
                Advancing multi-agent autonomous systems for global health. Exploring the intersection 
                of low-cost OpenFlexure hardware and high-performance cloud intelligence.
              </p>
              <div className="flex items-center gap-4">
                 <a href="#" className="text-slate-600 hover:text-cyan-400 transition-colors">
                   <Github size={20} />
                 </a>
              </div>
            </div>
            
            <div className="bg-slate-900/50 border border-slate-800 p-6 rounded-2xl max-w-xl backdrop-blur-sm">
              <div className="flex items-start gap-4">
                <div className="p-2 bg-amber-500/10 rounded-lg shrink-0">
                  <ShieldAlert className="text-amber-500" size={20} />
                </div>
                <div>
                  <h5 className="text-xs font-bold text-amber-500 uppercase tracking-widest mb-1">Research Beta Disclaimer</h5>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    MicroSmart PF is a proof-of-concept research agent. 
                    It is <strong className="text-slate-200">not a medical device</strong> and is not intended for clinical 
                    diagnosis. All outputs are generated by experimental AI models (YOLOv8 + Llama 3) 
                    and must be independently verified by qualified microscopists.
                  </p>
                </div>
              </div>
            </div>
          </div>
        ) : (
          // COMPACT FOOTER (Workbench)
          <div className="flex items-center justify-between gap-8">
             <div className="flex items-center gap-2 text-xs text-slate-500">
                <span className="font-bold text-slate-400">MicroSmart PF</span>
                <span className="w-1 h-1 bg-slate-700 rounded-full" />
                <span>v1.2 Beta</span>
             </div>

             <div className="flex items-center gap-3 bg-slate-900/50 px-3 py-1.5 rounded-lg border border-slate-800/50">
                <ShieldAlert className="text-amber-500/80" size={14} />
                <span className="text-[10px] text-slate-400">
                  Research Use Only. Not for Clinical Diagnosis.
                </span>
             </div>
          </div>
        )}
        
        {/* Copyright Line */}
        {!compact && (
          <div className="mt-12 pt-8 border-t border-slate-900 text-center text-[10px] text-slate-600 uppercase tracking-widest font-mono">
            © {new Date().getFullYear()} MicroSmart Multi-Agent Systems. Built for Research.
          </div>
        )}
      </div>
    </footer>
  );
};