import React from 'react';
import { AlertCircle } from 'lucide-react';

export const Footer: React.FC = () => {
  return (
    <footer className="bg-slate-50 border-t border-slate-200 py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row gap-8 items-start justify-between">
          <div className="max-w-md">
            <h4 className="text-slate-900 font-bold mb-2">MicroSmart Research Initiative</h4>
            <p className="text-sm text-slate-500 leading-relaxed">
              Advancing multi-agent autonomous systems for global health. This project explores 
              the intersection of low-cost hardware and high-performance cloud intelligence.
            </p>
          </div>
          
          <div className="bg-amber-50 border border-amber-100 p-4 rounded-xl max-w-xl">
            <div className="flex items-start">
              <AlertCircle className="text-amber-600 mt-0.5 shrink-0" size={18} />
              <div className="ml-3">
                <h5 className="text-sm font-bold text-amber-900 uppercase tracking-tight">Research Beta Disclaimer</h5>
                <p className="text-xs text-amber-800 mt-1 leading-normal">
                  MicroSmart PF is a proof-of-concept research agent in active development. 
                  It is <strong>not a medical device</strong> and is not intended for clinical 
                  diagnosis or treatment decisions. All outputs are generated by experimental AI models 
                  and must be independently verified by qualified researchers.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-8 pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
          © {new Date().getFullYear()} MicroSmart Multi-Agent Systems. Built for Research.
        </div>
      </div>
    </footer>
  );
};